version: '3'

services:
  express-app:
    build: .
    ports:
      - '3000:3000'
    depends_on:
      - db
    environment:
      DATABASE_URL: 'mongodb://monty:pass@db:27017/db?authSource=admin&directConnection=true'

  prisma-studio:
    build: .
    command: npx prisma studio --hostname 0.0.0.0 --port 5555
    ports:
      - '5555:5555'
    depends_on:
      - db
    environment:
      DATABASE_URL: 'mongodb://monty:pass@db:27017/db?authSource=admin&directConnection=true'

  db:
    image: prismagraphql/mongo-single-replica:4.4.3-bionic
    ports:
      - '27017:27017'
    environment:
      MONGO_INITDB_ROOT_USERNAME: monty
      MONGO_INITDB_ROOT_PASSWORD: pass
